### ISSUE TITLE
Multiple file or directory upload

### ISSUE THREAD

**Issue by foxylady2** [TOPdesk/nexus3-artifact-upload#2]
Hello. This is very helpful, thanks for it!

Is there any way to upload more than one file at a time or even a directory? If not, do you intend to add that feature soon?

**Comment by ghost** [comment]
Hi,

Thanks, glad that you find it helpful!

Multiple files or directory is not possible, and no plans for it at the moment, sorry about that. It would make the GAV part very complex, although it could work with the raw upload indeed, so if is a common use case than we might consider it, but that might be some time later… If someone implements it, we can accept a pull request on it of course ;)

**Comment by foxylady2** [comment]
hey,

Thanks for the info.

Uploading multiple files to raw would be great, indeed. I could totally use this feature but unfortunately don't have the skills to implement it myself as I'm still a beginner in this matter. I'll watch this repo in case someone does that.

Thanks again!

**Comment by mpiggott** [comment]
FYI the Nexus 3.9 release includes a UI for uploads which does support multiple files for some formats.

**Comment by ghost** [comment]
Yup, that is true indeed, time to retire this project :)
