### ISSUE TITLE
Upload md5, sha1

### ISSUE THREAD

**Issue by toudidel** [TOPdesk/nexus3-artifact-upload#3]
Is there any way to upload md5 & sha1 files (containing checksums of jar & pom files)?
I've received an error "Invalid path for a Maven 2 repository" when I try.

**Comment by ghost** [comment]
Hm. You may need to set the repo to permissive, as @nicolasrabier states it [here](https://github.com/nicolasrabier/nexus3-artifact-upload/commit/f07546559688bd6721c183a32cb700eaf7636c5d). Worst case you can try the raw upload, but the permissive layout policy may help in the GAV case too.

**Comment by toudidel** [comment]
You're right. Now it works. Thanks for advice.
